### ISSUE TITLE
"Missing Drupal:Calendar and Drupal:System

### ISSUE THREAD

**Issue by Codac12** [byuweb/calendar_widget_d7#2]
Drupal won't let me enable the module because of the "missing" things. I ensured I had the calendar module installed but it keeps saying that it is missing. (See image)
![screen shot 2017-05-17 at 4 53 35 pm](https://cloud.githubusercontent.com/assets/25096102/26179828/0939d096-3b23-11e7-929f-5fb948e7150e.png)

**Comment by katrialesser** [comment]
@Codac12 what version of Drupal are you using? There is a format in the module that requires Drupal 7.40 or later. Drupal 7 is now on 7.56.
Also, it appears you are on an old version of the module. I removed the Calendar requirement as it technically isn't needed, so I suggest pulling the most recent version of the module and trying again. If you are on a Drupal core version prior to 7.40 you'll really need to perform core updates.

related lines in .info file:
#dependencies[] = calendar:calendar
dependencies[] = drupal:system (>= 7.40)

**Comment by rburkey87** [comment]
was resolved via Slack (#byu-theme-help) on May 19th, 2017.
