### ISSUE TITLE
Trim string error

### ISSUE THREAD

**Issue by rburkey87** [byuweb/calendar_widget_d7#5]
Returning these errors:

`Warning: trim() expects parameter 1 to be string, array given in calendar_widget_d7_fullpage_rows() (line 601 of C:\xampp\htdocs\byu_garland_d7\sites\all\modules\calendar_widget_d7\calendar_widget_d7.module).`

`Warning: trim() expects parameter 1 to be string, array given in calendar_widget_d7_fullpage_image_rows() (line 675 of C:\xampp\htdocs\byu_garland_d7\sites\all\modules\calendar_widget_d7\calendar_widget_d7.module).`

**Comment by katrialesser** [comment]
You'll need to add more details about when this happens. What criteria/parameters to reproduce @rburkey87 ?

**Comment by rburkey87** [comment]
no longer seems to be returning any errors.
